// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';
import {main} from '../models';
import {strength} from '../models';
import {gen} from '../models';

export function AnalyzeSecurity():Promise<vault.Report>;

export function ChangeMasterPassword(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function ChooseBackupFile():Promise<string>;

export function ChooseBackupPath():Promise<string>;

export function ClearClipboard():Promise<boolean>;

export function CopyEntryField(arg1:string,arg2:string):Promise<main.CopyFieldResult>;

export function CreateVault(arg1:Array<number>):Promise<void>;

export function CurrentGeneration():Promise<number>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DescribeBackup(arg1:string):Promise<vault.BackupInfo>;

export function EvaluateStrength(arg1:string):Promise<strength.Result>;

export function ExportBackup(arg1:string,arg2:Array<number>):Promise<vault.BackupResult>;

export function GeneratePassphrase(arg1:number,arg2:string):Promise<string>;

export function GeneratePassword(arg1:gen.Options):Promise<string>;

export function GetAllTags():Promise<Array<string>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDefaultGeneratorOptions():Promise<gen.Options>;

export function GetEntry(arg1:string):Promise<vault.Detail>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<vault.Status>;

export function GetTOTPCode(arg1:string):Promise<main.TOTPResult>;

export function ImportBackup(arg1:string,arg2:Array<number>):Promise<vault.BackupInfo>;

export function ListEntries():Promise<Array<vault.Summary>>;

export function Lock():Promise<void>;

export function LockIfBlurred():Promise<boolean>;

export function LockIfMinimized():Promise<boolean>;

export function NotifyActivity():Promise<void>;

export function ParseTOTPURI(arg1:string):Promise<main.TOTPParsed>;

export function Ping():Promise<boolean>;

export function RevealPassword(arg1:string):Promise<main.RevealResult>;

export function SaveEntry(arg1:vault.EntryInput):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SuggestBackupPath():Promise<string>;

export function SymbolChars():Promise<string>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function Unlock(arg1:Array<number>):Promise<void>;
