// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSecurity() {
  return window['go']['main']['App']['AnalyzeSecurity']();
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function ChooseBackupFile() {
  return window['go']['main']['App']['ChooseBackupFile']();
}

export function ChooseBackupPath() {
  return window['go']['main']['App']['ChooseBackupPath']();
}

export function ClearClipboard() {
  return window['go']['main']['App']['ClearClipboard']();
}

export function CopyEntryField(arg1, arg2) {
  return window['go']['main']['App']['CopyEntryField'](arg1, arg2);
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function CurrentGeneration() {
  return window['go']['main']['App']['CurrentGeneration']();
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DescribeBackup(arg1) {
  return window['go']['main']['App']['DescribeBackup'](arg1);
}

export function EvaluateStrength(arg1) {
  return window['go']['main']['App']['EvaluateStrength'](arg1);
}

export function ExportBackup(arg1, arg2) {
  return window['go']['main']['App']['ExportBackup'](arg1, arg2);
}

export function GeneratePassphrase(arg1, arg2) {
  return window['go']['main']['App']['GeneratePassphrase'](arg1, arg2);
}

export function GeneratePassword(arg1) {
  return window['go']['main']['App']['GeneratePassword'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDefaultGeneratorOptions() {
  return window['go']['main']['App']['GetDefaultGeneratorOptions']();
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTOTPCode(arg1) {
  return window['go']['main']['App']['GetTOTPCode'](arg1);
}

export function ImportBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2);
}

export function ListEntries() {
  return window['go']['main']['App']['ListEntries']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function LockIfBlurred() {
  return window['go']['main']['App']['LockIfBlurred']();
}

export function LockIfMinimized() {
  return window['go']['main']['App']['LockIfMinimized']();
}

export function NotifyActivity() {
  return window['go']['main']['App']['NotifyActivity']();
}

export function ParseTOTPURI(arg1) {
  return window['go']['main']['App']['ParseTOTPURI'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RevealPassword(arg1) {
  return window['go']['main']['App']['RevealPassword'](arg1);
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SuggestBackupPath() {
  return window['go']['main']['App']['SuggestBackupPath']();
}

export function SymbolChars() {
  return window['go']['main']['App']['SymbolChars']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}
